### ISSUE TITLE
Invalid CSRF token.

### ISSUE THREAD

**Issue by JoelTwilo** [LionwareSolutions/symfony-session-timeout#1]
When I've been logged out using this bundle and try to log back in the CSRF token doesn't regenerate. I have to refresh the login form for it to work again.

I'm using FOSUserBundle, I don't know it's because of that.

**Comment by NickStemerdink** [comment]
Thanks for your ticket.

It seems unlikely that this is being caused by this bundle.

Can you try to reproduce the scenario without this bundle?

1. Remove the LionwareSolutions/symfony-session-timeout bundle
2. Log in to your application
3. Remove your session cookie
4. Reload the page (this should redirect you to the login page)
5. Log back in

**Comment by JoelTwilo** [comment]
I have done all of the steps above, and I was able to log back in without any problems.

**Comment by NickStemerdink** [comment]
I am not able to reproduce this behaviour. The only thing this bundle actually does is invalidate the session after a certain period of inactivity. The rest is handled by the application, like redirecting to the login page etc.

I'm closing the issue because of that, but please feel free to prove the issue.
